
package visao;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import beans.BeansAgenda;
import connection.ConexBD;
import modeloDAO.DaoAgenda;

/**
 *
 * @author Manoel Olivio de Mediros
 */
public class FrmAgenda extends javax.swing.JFrame {
    DaoAgenda control = new DaoAgenda();
    BeansAgenda agenda = new BeansAgenda();
        
    
    Calendar data = Calendar.getInstance();
        Date dt = data.getTime();
       // SimpleDateFormat dateFormat  = new SimpleDateFormat("yyyy/mm/aa");
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
        String dthoje;
        String status = "Aberto";
        
      /**
     * Creates new form FrmAgenda
     */
    public FrmAgenda() {
        initComponents();
        dthoje = formato.format(dt);
        txtDataHoje.setText(dthoje);
        preencherTabAgenda();
       
        
    }

    public void preencherTabAgenda(){
   
               
        DaoAgenda daoag = new DaoAgenda();
        List<BeansAgenda> listagenda = daoag.agenda(agenda);
        DefaultTableModel tabagenda = (DefaultTableModel) tabelaAtenderAgenda.getModel();
        tabagenda.setNumRows(0);
         //  DEFINE A LARGURA DA COLUNA
         tabelaAtenderAgenda.setAutoResizeMode(tabelaAtenderAgenda.AUTO_RESIZE_OFF);  
         tabelaAtenderAgenda.getColumnModel().getColumn(0).setPreferredWidth(80);
         tabelaAtenderAgenda.getColumnModel().getColumn(1).setPreferredWidth(150);
         tabelaAtenderAgenda.getColumnModel().getColumn(2).setPreferredWidth(150);
         tabelaAtenderAgenda.getColumnModel().getColumn(3).setPreferredWidth(110);
         tabelaAtenderAgenda.getColumnModel().getColumn(4).setPreferredWidth(50);
       for (BeansAgenda c : listagenda){
       Object[] obj = new Object[]{
           c.getCodigoagenda(),
           c.getNomemedico(),
           c.getNomepaciente(),
           c.getData(),
           c.getStatusagenda(),
           
       };
       tabagenda.addRow(obj);
       }  
         
     }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAtenderAgenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAtenderAgenda = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoAgenda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAtualizarAgenda = new javax.swing.JButton();
        txtDataHoje = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agenda");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAtenderAgenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtenderAgenda.setText("Atender Agendamento");
        btnAtenderAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderAgendaActionPerformed(evt);
            }
        });

        tabelaAtenderAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Agenda", "Médico", "Paciente", "Data Consulta", "Status"
            }
        ));
        tabelaAtenderAgenda.setRowHeight(18);
        tabelaAtenderAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAtenderAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAtenderAgenda);

        jLabel2.setText("Codigo Agenda:");

        txtCodigoAgenda.setEnabled(false);

        jButton1.setText("Novo Agendamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAtualizarAgenda.setForeground(new java.awt.Color(0, 153, 0));
        btnAtualizarAgenda.setText("Atualizar Agenda");
        btnAtualizarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnAtenderAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarAgenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtenderAgenda)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        txtDataHoje.setForeground(new java.awt.Color(204, 0, 0));
        txtDataHoje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataHoje.setCaretColor(new java.awt.Color(153, 0, 0));
        txtDataHoje.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(717, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderAgendaActionPerformed
        // TODO add your handling code here:
        String status = "em atendimento"; 
        DaoAgenda dao = new DaoAgenda();
         BeansAgenda agen = new BeansAgenda();
        agen.setCodigoagenda(Integer.parseInt(txtCodigoAgenda.getText()));
        agen.setStatusagenda(status);
        dao.AtenderAg(agen);
        preencherTabAgenda();
    }//GEN-LAST:event_btnAtenderAgendaActionPerformed

    private void tabelaAtenderAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAtenderAgendaMouseClicked
        // TODO add your handling code here:
       
        txtCodigoAgenda.setText(tabelaAtenderAgenda.getValueAt(tabelaAtenderAgenda.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tabelaAtenderAgendaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmAgendamento telaAg = new FrmAgendamento();
          telaAg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAtualizarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarAgendaActionPerformed
        // TODO add your handling code here:
         preencherTabAgenda();
    }//GEN-LAST:event_btnAtualizarAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenderAgenda;
    private javax.swing.JButton btnAtualizarAgenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAtenderAgenda;
    private javax.swing.JTextField txtCodigoAgenda;
    private javax.swing.JFormattedTextField txtDataHoje;
    // End of variables declaration//GEN-END:variables
}
