/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import beans.BeansAgenda;
import connection.ConexBD;
import modeloDAO.DaoAgenda;

/**
 *
 * @author olivi
 */
public class FrmAgendaMedica extends javax.swing.JFrame {
    Connection conex = new ConexBD().Conecta();
    BeansAgenda agenda = new BeansAgenda();
    DaoAgenda daoag = new DaoAgenda();
    

    /**
     * Creates new form frmAgendaMedica
     */
    public FrmAgendaMedica() {
          initComponents();
        
          preencherMedicos();
          preencherAgendaMedico();
          tabelaAgendaMedica.setEnabled(false);
    }
    
    public void preencherMedicos(){
     
       List<String> medList = new ArrayList<String>();
       String sql = "SELECT * FROM medicos";

        try {
            PreparedStatement stmt = conex.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()){
            medList.add(rs.getString("nome_medico"));
            DefaultComboBoxModel medBox = new DefaultComboBoxModel(medList.toArray());
            cmbAgendaMedica.setModel(medBox);
         }
           stmt.close();
           rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao preencher Medicos" + ex.getMessage());
        }

     }
    
    public void preencherAgendaMedico(){
        DaoAgenda daoagmed = new DaoAgenda();
        List<BeansAgenda> listagenda = daoagmed.agenMedica(agenda);
        DefaultTableModel tabagenda = (DefaultTableModel) tabelaAgendaMedica.getModel();
        tabagenda.setNumRows(0);
         //  DEFINE A LARGURA DA COLUNA
         tabelaAgendaMedica.setAutoResizeMode(tabelaAgendaMedica.AUTO_RESIZE_OFF);  
         tabelaAgendaMedica.getColumnModel().getColumn(0).setPreferredWidth(60);
         tabelaAgendaMedica.getColumnModel().getColumn(1).setPreferredWidth(60);
         tabelaAgendaMedica.getColumnModel().getColumn(2).setPreferredWidth(160);
         tabelaAgendaMedica.getColumnModel().getColumn(3).setPreferredWidth(80);
         tabelaAgendaMedica.getColumnModel().getColumn(4).setPreferredWidth(120);
         tabelaAgendaMedica.getColumnModel().getColumn(5).setPreferredWidth(120);
         
       for (BeansAgenda c : listagenda){
       Object[] obj = new Object[]{
           c.getCodigoagenda(),
           c.getCodigopaciente(),
           c.getNomepaciente(),
           c.getDtNasPac(),
           c.getMotivogenda(),
           c.getStatusagenda(),
           
       };
       tabagenda.addRow(obj);
       }  
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgendaMedica = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAtenderPaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbAgendaMedica = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda Médica");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Agenda Médica");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaAgendaMedica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Ag.", "Cod.Pac.", "Paciente", "Dt.Nacto", "motivo", "Status"
            }
        ));
        tabelaAgendaMedica.setRowHeight(18);
        tabelaAgendaMedica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendaMedicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAgendaMedica);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Agenda Paciente");

        btnAtenderPaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtenderPaciente.setText("Atender Paciente");
        btnAtenderPaciente.setEnabled(false);
        btnAtenderPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAtenderPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAtenderPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Médico:");

        cmbAgendaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgendaMedicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbAgendaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAgendaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(672, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAgendaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgendaMedicaActionPerformed
        
        btnAtenderPaciente.setEnabled(true);
       int cod =  daoag.BuscarMedAg((String) cmbAgendaMedica.getSelectedItem());
       // String codigo = String.valueOf(cod);
         String status = "em atendimento";
        DaoAgenda daoagmed = new DaoAgenda();
        agenda.setCodigomedico(cod);
        agenda.setStatusagenda(status);
        tabelaAgendaMedica.setEnabled(true);
        List<BeansAgenda> listagenda = daoagmed.atendMedica(agenda);
        DefaultTableModel tabagenda = (DefaultTableModel) tabelaAgendaMedica.getModel();
        tabagenda.setNumRows(0);
       for (BeansAgenda c : listagenda){
       Object[] obj = new Object[]{
           c.getCodigoagenda(),
           c.getCodigopaciente(),
           c.getNomepaciente(),
           c.getDtNasPac(),
           c.getMotivogenda(),
           c.getStatusagenda(),
           
       };
       tabagenda.addRow(obj);
       }  
         
        
    }//GEN-LAST:event_cmbAgendaMedicaActionPerformed

    private void btnAtenderPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderPacienteActionPerformed
        
        BeansAgenda agenda =  new BeansAgenda();
        agenda.setNomemedico((String) cmbAgendaMedica.getSelectedItem());
        agenda.setCodagconsulta(tabelaAgendaMedica.getValueAt(tabelaAgendaMedica.getSelectedRow(), 0).toString());
        agenda.setNomepaciente(tabelaAgendaMedica.getValueAt(tabelaAgendaMedica.getSelectedRow(), 2).toString());
        agenda.setDtNasPac(tabelaAgendaMedica.getValueAt(tabelaAgendaMedica.getSelectedRow(), 3).toString());
        agenda.setMotivogenda(tabelaAgendaMedica.getValueAt(tabelaAgendaMedica.getSelectedRow(), 4).toString());
              
        FrmConsulta telaConsulta = new FrmConsulta();
        telaConsulta.exportagenda(agenda);
        telaConsulta.setVisible(true);
        
        
         
    }//GEN-LAST:event_btnAtenderPacienteActionPerformed

    private void tabelaAgendaMedicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendaMedicaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabelaAgendaMedicaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgendaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenderPaciente;
    private javax.swing.JComboBox<String> cmbAgendaMedica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAgendaMedica;
    // End of variables declaration//GEN-END:variables
}
